using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using MLab.ShadowFramework.Interpolation;

namespace MLab.ShadowFramework.Processes
{
    /*This is a structural output generated by a Full Tessellation Process
     and required during updates*/
    public class TessellationOutput
    {
        private int builtVerticesSize;
        private int[] builtTrianglesSize;
        private CPNGuide[] guides;
        private int[] edgesProfile;

        private int[][] polygonsProfile;
        private int[][] polygonsVerticesProfile;
        private CPNPolygon[][] polygons; 
        private int edgesBuiltVerticesSize;  

        public int GetBuiltVerticesSize() {
            return this.builtVerticesSize;
        }

        public void SetBuiltVerticesSize(int builtVerticesSize) {
            this.builtVerticesSize=builtVerticesSize;
        }

        public int GetEdgesBuiltVerticesSize() {
            return this.edgesBuiltVerticesSize;
        }

        public void SetEdgesBuiltVerticesSize(int edgesBuiltVerticesSize)
        {
            this.edgesBuiltVerticesSize = edgesBuiltVerticesSize;
        }

        public int[] GetBuiltTrianglesSize()
        {
            return this.builtTrianglesSize;
        }

        public void InitBuiltTrianglesSize(int builtTrianglesSizeLength)
        {
            this.builtTrianglesSize = new int[builtTrianglesSizeLength];
        }

        public CPNGuide[] GetGuides()
        {
            return this.guides;
        }

        public CPNGuide[] InitGuides(int guidesLength)
        {
            this.guides = new CPNGuide[guidesLength];
            return this.guides;
        }

        public int[] GetEdgesProfile()
        {
            return this.edgesProfile;
        }

        public int[] InitEdgesProfile(int edgesProfileLength)
        {
            this.edgesProfile = new int[edgesProfileLength];
            return edgesProfile;
        }

        public int[][] InitPolygonsProfile(int polygonsProfileLength)
        {
            this.polygonsProfile = new int[polygonsProfileLength][];
            this.polygonsVerticesProfile = new int[polygonsProfileLength][];
            return polygonsProfile;
        }

        public int[][] GetPolygonsProfile()
        {
            return this.polygonsProfile;
        }

        public int[][] GetPolygonsVerticesProfile()
        {
            return this.polygonsVerticesProfile;
        }

        public CPNPolygon[][] GetPolygons()
        {
            return this.polygons;
        }

        public CPNPolygon[][] InitPolygons(int polygonsLength)
        {
            this.polygons = new CPNPolygon[polygonsLength][];
            return this.polygons;
        }
         
    }
}
